% Copyright (c) 2014 Institute for Theoretical Information Technology,
%                    RWTH Aachen University
%
% This software may be modified and distributed under the terms of the MIT
% license. See the LICENSE file for details.

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{tiarticle}[2014/12/09 v0.1]

\ProcessOptions\relax

% Load the base class.
\LoadClass[12pt,a4paper]{article}

% Page layout
\setlength{\textheight}{25.5truecm}
\setlength{\textwidth}{16.2truecm}
\hoffset=-1cm
\voffset=-2cm
\pagestyle{empty}
\parindent=0pt
\parskip=5pt

\endinput

